
services:
    nginx-{{project_urlsafe}}:
      container_name: nginx-{{project_urlsafe}}
      image: nginx:latest
      ports:
        - "8080:80"
      volumes:
        - ./docker/nginx-config/default.conf:/etc/nginx/conf.d/default.conf
      networks:
        - {{project_urlsafe}}-network

    db-{{project_urlsafe}}:
      container_name: db-{{project_urlsafe}}
      image: postgis/postgis:14-3.2
      volumes:
        - ../../{{project}}-postgres-data:/var/lib/postgresql/data
        - ../../{{project}}-postgres-log:/var/log/postgresql
        - ./docker/init-unix.sql:/docker-entrypoint-initdb.d/init.sql # to set up the DB template
      ports:
        - '5433:5432'
      env_file: 
        - ./docker/env_file.env
      networks:
        - {{project_urlsafe}}-network

    elastic-bindmount-init-{{project_urlsafe}}:
      image: alpine
      container_name: elastic-bindmount-init-{{project_urlsafe}}
      restart: "no"
      entrypoint: |
        /bin/sh -c "chown 1000:1000 /esBindMount"
      volumes:
        - ../../{{project}}-elasticsearch-data:/esBindMount


    elasticsearch-{{project_urlsafe}}:
      container_name: elasticsearch-{{project_urlsafe}}
      image: elasticsearch:8.5.0
      volumes:
        #- ../../elasticsearch_data_{{project}}:/usr/share/elasticsearch/data
        - ../../{{project}}-elasticsearch-data:/usr/share/elasticsearch/data
      ports:
        - "9201:9200"
        - "9301:9300"
      env_file: 
        - ./docker/env_file.env
      networks:
        - {{project_urlsafe}}-network
      depends_on:
        - elastic-bindmount-init-{{project_urlsafe}}

    rabbitmq-{{project_urlsafe}}:
      container_name: rabbitmq-{{project_urlsafe}}
      image: rabbitmq:3.8-management
      hostname: my-rabbit
      volumes:
        - rabbitmq-data:/var/lib/rabbitmq/mnesia/rabbit@my-rabbit
        - rabbitmq-logs:/var/log/rabbitmq/log
      ports:
        - 5673:5672
        - 15673:15672
      networks:
        - {{project_urlsafe}}-network

    #pg-feat-{{project_urlsafe}}:
    #  container_name: pg-feat-{{project_urlsafe}}
    #  image: pramsey/pg_featureserv
    #  volumes:
    #    - ../../pg_featureserv_config_{{project}}:/config
    #  environment:
    #    - DATABASE_URL=postgresql://arches_spatial_views:arches_spatial_views@db-{{project_urlsafe}}:5432/{{project}}
    #  ports:
    #    - 9000:9000
    #  networks:
    #    - {{project_urlsafe}}-network
    #  depends_on:
    #    - db-{{project_urlsafe}}
    
    #pg-tile-{{project_urlsafe}}:
    #  container_name: pg-tile-{{project_urlsafe}}
    #  image: pramsey/pg_tileserv
    #  volumes:
    #    - ../../pg_tileserv_config_{{project}}:/config
    #  environment:
    #    - DATABASE_URL=postgresql://arches_spatial_views:arches_spatial_views@db-{{project_urlsafe}}:5432/{{project}}
    #  ports:
    #    - 7800:7800
    #  networks:
    #    - {{project_urlsafe}}-network
    #  depends_on:
    #    - db-{{project_urlsafe}}


networks:
  {{project_urlsafe}}-network:
    name: {{project_urlsafe}}-network
    driver: bridge

volumes:
    rabbitmq-logs:
    rabbitmq-data: